/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as IndexRouteImport } from './routes/index'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consulting': typeof ConsultingRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consulting': typeof ConsultingRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consulting': typeof ConsultingRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/consulting' | '/dashboard' | '/faq' | '/pricing' | '/products'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/consulting' | '/dashboard' | '/faq' | '/pricing' | '/products'
  id:
    | '__root__'
    | '/'
    | '/consulting'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultingRoute: typeof ConsultingRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultingRoute: ConsultingRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
