/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiRetellWebhookRouteImport } from './routes/api/retell/webhook'
import { Route as ApiDemoWebCallRouteImport } from './routes/api/demo/web-call'
import { Route as AdminCustomersIdRouteImport } from './routes/admin/customers.$id'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiRetellWebhookRoute = ApiRetellWebhookRouteImport.update({
  id: '/api/retell/webhook',
  path: '/api/retell/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoWebCallRoute = ApiDemoWebCallRouteImport.update({
  id: '/api/demo/web-call',
  path: '/api/demo/web-call',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/agent': typeof AgentRoute
  '/consulting': typeof ConsultingRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/api/demo/web-call': typeof ApiDemoWebCallRoute
  '/api/retell/webhook': typeof ApiRetellWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/consulting': typeof ConsultingRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin': typeof AdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/api/demo/web-call': typeof ApiDemoWebCallRoute
  '/api/retell/webhook': typeof ApiRetellWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/agent': typeof AgentRoute
  '/consulting': typeof ConsultingRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/api/demo/web-call': typeof ApiDemoWebCallRoute
  '/api/retell/webhook': typeof ApiRetellWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/consulting'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/products'
    | '/admin/login'
    | '/admin/new'
    | '/admin/'
    | '/admin/customers/$id'
    | '/api/demo/web-call'
    | '/api/retell/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/consulting'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/products'
    | '/admin/login'
    | '/admin/new'
    | '/admin'
    | '/admin/customers/$id'
    | '/api/demo/web-call'
    | '/api/retell/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/consulting'
    | '/dashboard'
    | '/faq'
    | '/pricing'
    | '/products'
    | '/admin/login'
    | '/admin/new'
    | '/admin/'
    | '/admin/customers/$id'
    | '/api/demo/web-call'
    | '/api/retell/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AgentRoute: typeof AgentRoute
  ConsultingRoute: typeof ConsultingRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRoute
  ApiDemoWebCallRoute: typeof ApiDemoWebCallRoute
  ApiRetellWebhookRoute: typeof ApiRetellWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/retell/webhook': {
      id: '/api/retell/webhook'
      path: '/api/retell/webhook'
      fullPath: '/api/retell/webhook'
      preLoaderRoute: typeof ApiRetellWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/web-call': {
      id: '/api/demo/web-call'
      path: '/api/demo/web-call'
      fullPath: '/api/demo/web-call'
      preLoaderRoute: typeof ApiDemoWebCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminNewRoute: AdminNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AgentRoute: AgentRoute,
  ConsultingRoute: ConsultingRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRoute,
  ApiDemoWebCallRoute: ApiDemoWebCallRoute,
  ApiRetellWebhookRoute: ApiRetellWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
