/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as StoreRouteImport } from './routes/store'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as BookRouteImport } from './routes/book'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiRetellWebhookRouteImport } from './routes/api/retell/webhook'
import { Route as ApiDemoWebCallRouteImport } from './routes/api/demo/web-call'
import { Route as AdminCustomersIdRouteImport } from './routes/admin/customers.$id'

const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiRetellWebhookRoute = ApiRetellWebhookRouteImport.update({
  id: '/api/retell/webhook',
  path: '/api/retell/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoWebCallRoute = ApiDemoWebCallRouteImport.update({
  id: '/api/demo/web-call',
  path: '/api/demo/web-call',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/agent': typeof AgentRoute
  '/agents': typeof AgentsRoute
  '/book': typeof BookRoute
  '/consulting': typeof ConsultingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRoute
  '/faq': typeof FaqRoute
  '/marketing': typeof MarketingRoute
  '/philosophy': typeof PhilosophyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/store': typeof StoreRoute
  '/strategy': typeof StrategyRoute
  '/terms': typeof TermsRoute
  '/websites': typeof WebsitesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/api/demo/web-call': typeof ApiDemoWebCallRoute
  '/api/retell/webhook': typeof ApiRetellWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent': typeof AgentRoute
  '/agents': typeof AgentsRoute
  '/book': typeof BookRoute
  '/consulting': typeof ConsultingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRoute
  '/faq': typeof FaqRoute
  '/marketing': typeof MarketingRoute
  '/philosophy': typeof PhilosophyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/store': typeof StoreRoute
  '/strategy': typeof StrategyRoute
  '/terms': typeof TermsRoute
  '/websites': typeof WebsitesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin': typeof AdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/api/demo/web-call': typeof ApiDemoWebCallRoute
  '/api/retell/webhook': typeof ApiRetellWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/agent': typeof AgentRoute
  '/agents': typeof AgentsRoute
  '/book': typeof BookRoute
  '/consulting': typeof ConsultingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRoute
  '/faq': typeof FaqRoute
  '/marketing': typeof MarketingRoute
  '/philosophy': typeof PhilosophyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/store': typeof StoreRoute
  '/strategy': typeof StrategyRoute
  '/terms': typeof TermsRoute
  '/websites': typeof WebsitesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/api/demo/web-call': typeof ApiDemoWebCallRoute
  '/api/retell/webhook': typeof ApiRetellWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/agent'
    | '/agents'
    | '/book'
    | '/consulting'
    | '/contact'
    | '/dashboard'
    | '/dashboards'
    | '/faq'
    | '/marketing'
    | '/philosophy'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/store'
    | '/strategy'
    | '/terms'
    | '/websites'
    | '/admin/login'
    | '/admin/new'
    | '/admin/'
    | '/admin/customers/$id'
    | '/api/demo/web-call'
    | '/api/retell/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agent'
    | '/agents'
    | '/book'
    | '/consulting'
    | '/contact'
    | '/dashboard'
    | '/dashboards'
    | '/faq'
    | '/marketing'
    | '/philosophy'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/store'
    | '/strategy'
    | '/terms'
    | '/websites'
    | '/admin/login'
    | '/admin/new'
    | '/admin'
    | '/admin/customers/$id'
    | '/api/demo/web-call'
    | '/api/retell/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/agent'
    | '/agents'
    | '/book'
    | '/consulting'
    | '/contact'
    | '/dashboard'
    | '/dashboards'
    | '/faq'
    | '/marketing'
    | '/philosophy'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/store'
    | '/strategy'
    | '/terms'
    | '/websites'
    | '/admin/login'
    | '/admin/new'
    | '/admin/'
    | '/admin/customers/$id'
    | '/api/demo/web-call'
    | '/api/retell/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AgentRoute: typeof AgentRoute
  AgentsRoute: typeof AgentsRoute
  BookRoute: typeof BookRoute
  ConsultingRoute: typeof ConsultingRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DashboardsRoute: typeof DashboardsRoute
  FaqRoute: typeof FaqRoute
  MarketingRoute: typeof MarketingRoute
  PhilosophyRoute: typeof PhilosophyRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  StoreRoute: typeof StoreRoute
  StrategyRoute: typeof StrategyRoute
  TermsRoute: typeof TermsRoute
  WebsitesRoute: typeof WebsitesRoute
  ApiDemoWebCallRoute: typeof ApiDemoWebCallRoute
  ApiRetellWebhookRoute: typeof ApiRetellWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/retell/webhook': {
      id: '/api/retell/webhook'
      path: '/api/retell/webhook'
      fullPath: '/api/retell/webhook'
      preLoaderRoute: typeof ApiRetellWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/web-call': {
      id: '/api/demo/web-call'
      path: '/api/demo/web-call'
      fullPath: '/api/demo/web-call'
      preLoaderRoute: typeof ApiDemoWebCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminNewRoute: AdminNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AgentRoute: AgentRoute,
  AgentsRoute: AgentsRoute,
  BookRoute: BookRoute,
  ConsultingRoute: ConsultingRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DashboardsRoute: DashboardsRoute,
  FaqRoute: FaqRoute,
  MarketingRoute: MarketingRoute,
  PhilosophyRoute: PhilosophyRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  StoreRoute: StoreRoute,
  StrategyRoute: StrategyRoute,
  TermsRoute: TermsRoute,
  WebsitesRoute: WebsitesRoute,
  ApiDemoWebCallRoute: ApiDemoWebCallRoute,
  ApiRetellWebhookRoute: ApiRetellWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
